#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${ID}
#            client-secret: ${SECRET}
#            scope:
#              - email
#              - profile